kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pvdabbeele
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-pvdabbeele
  volumeMode: Filesystem
